# Generated by Django 2.2 on 2019-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calltracker', '0002_auto_20190406_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_types', models.CharField(choices=[('SA', 'Sale'), ('NS', 'No Sale'), ('SU', 'Subscriber'), ('MR', 'Misrouted'), ('IN', 'Invalid')], default='SA', max_length=2)),
            ],
        ),
    ]
